#! bash
#
# compile host side application
#
# Usage: buildhostscript              compile all the targets
#        buildhostscript /CLEAN       deletes all the intermediate files
#        buildhostscript /REBUILD     rebuild all the targets
#
# if Visual Studio is not installed, do nothing.
#

TARGETS="viewer_server/viewerServer color/HioSample HIODemo/HIODemo viewer/usbsample"

if [ "$NDEBUG" == "TRUE" ]
then
    tgt="ALL - RELEASE";
else
    tgt="ALL - DEBUG";
fi

if [ "$1" == "/CLEAN" ]
then
    tgt="ALL"
fi

if [ "$MSDEVDIR" == "" ]
then
    echo Visual Studio is not installed. Do nothing.
else

    MSDEV=$MSDEVDIR/Bin/msdev.exe

    for t in $TARGETS; do \
        "$MSDEV" vc++/$t.dsw /MAKE "$tgt" $1;
    done

    if [ "$1" = "/CLEAN" ] ; then \
        echo clean ; \
    fi
fi

